// <auto-generated />
namespace LMSweb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_columns_mission_and_course : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_columns_mission_and_course));
        
        string IMigrationMetadata.Id
        {
            get { return "202304231634214_add_columns_mission_and_course"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
