// <auto-generated />
namespace LMSweb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class alter_col_student_gid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alter_col_student_gid));
        
        string IMigrationMetadata.Id
        {
            get { return "202305010138152_alter_col_student_gid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
