// <auto-generated />
namespace LMSweb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class drop_cloumn_relatedKP : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(drop_cloumn_relatedKP));
        
        string IMigrationMetadata.Id
        {
            get { return "202304180203372_drop_cloumn_relatedKP"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
