// <auto-generated />
namespace LMSweb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class fix_foreign : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix_foreign));
        
        string IMigrationMetadata.Id
        {
            get { return "202306271158170_fix_foreign"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
